### ISSUE TITLE
(/ 51600 3000000) signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by tiancaiamao** [tiancaiamao/shen-go#12]
unexpected fault address 0xf44480
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf44480 pc=0x8d179e]

```
goroutine 1 [running]:
runtime.throw(0x98993c, 0x5)
        /media/genius/OS/project/go/src/runtime/panic.go:1116 +0x72 fp=0xc000147998 sp=0xc000147968 pc=0x58e6b2
runtime.sigpanic()
        /media/genius/OS/project/go/src/runtime/signal_unix.go:727 +0x405 fp=0xc0001479c8 sp=0xc000147998 pc=0x5a4be5
github.com/tiancaiamao/shen-go/kl.(*KLambda).eval(0xc0000902a0, 0xc0000902a0)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/klambda.go:114 +0x7e fp=0xc000147b10 sp=0xc0001479c8 pc=0x8d179e
github.com/tiancaiamao/shen-go/kl.(*ControlFlow).trampoline(0xc0000902a0, 0xa0f180, 0xc0000902a0, 0xc74750)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/eval.go:62 +0x77 fp=0xc000147b38 sp=0xc000147b10 pc=0x8ce8b7
github.com/tiancaiamao/shen-go/kl.(*ControlFlow).evalExp(0xc0000902a0, 0xa0f180, 0xc0000902a0, 0xf44480, 0xc0000a0020, 0xc74750)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/eval.go:54 +0xd2 fp=0xc000147b90 sp=0xc000147b38 pc=0x8ce712
github.com/tiancaiamao/shen-go/kl.(*KLambda).eval(0xc0000902a0, 0xc0000902a0)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/klambda.go:181 +0x393 fp=0xc000147cd8 sp=0xc000147b90 pc=0x8d1ab3
github.com/tiancaiamao/shen-go/kl.(*ControlFlow).trampoline(0xc0000902a0, 0xa0f180, 0xc0000902a0, 0x1)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/eval.go:62 +0x77 fp=0xc000147d00 sp=0xc000147cd8 pc=0x8ce8b7
github.com/tiancaiamao/shen-go/kl.(*ControlFlow).evalExp(0xc0000902a0, 0xa0f180, 0xc0000902a0, 0xc0000a0220, 0xc0000a0020, 0x0)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/eval.go:54 +0xd2 fp=0xc000147d58 sp=0xc000147d00 pc=0x8ce712
github.com/tiancaiamao/shen-go/kl.(*KLambda).Eval(0xc0000902a0, 0xc0000a0220, 0x0)
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/kl/klambda.go:99 +0x93 fp=0xc000147db8 sp=0xc000147d58 pc=0x8d1473
main.main()
        /media/genius/OS/project/src/github.com/tiancaiamao/shen-go/cmd/kl/main.go:71 +0x3b6 fp=0xc000147f88 sp=0xc000147db8 pc=0x8dd296
runtime.main()
        /media/genius/OS/project/go/src/runtime/proc.go:204 +0x209 fp=0xc000147fe0 sp=0xc000147f88 pc=0x5910c9
runtime.goexit()
        /media/genius/OS/project/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000147fe8 sp=0xc000147fe0 pc=0x5c68a1
```

**Comment by tiancaiamao** [comment]
A minimal reproduce can be just 
```
#> 3000000
```
